In [1]:
import pandas as pd
import numpy as np
import re

In [8]:
total = pd.read_csv("datasets/1.-Transportation/accidents-2017.csv")

In [9]:
total.head()

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
2,2017S010210,Unknown,Unknown,Litoral (Besòs) ...,Friday,December,8,21,Afternoon,5,0,5,2,2.167356,41.360885
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365

In [10]:
holiday_acc = pd.read_csv("datasets/1.-Transportation/accidents-holidays.csv")

In [31]:
holiday_acc['Day'] = holiday_acc.Day.astype(str)

In [33]:
holiday_acc["Date"] = holiday_acc["Month"] + " " + holiday_acc["Day"]

In [35]:
holiday_acc.to_csv("datasets/1.-Transportation/new_holiday.csv")

In [22]:
serious_hol = holiday_acc.sort_values("Serious injuries", ascending=False)

In [23]:
serious_hol.head(30)

,Unnamed: 0,District Name,Weekday,Month,Day,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved
562,562,Les Corts,Sunday,June,4,Morning,3,4,7,2
641,641,Sant Martí,Sunday,April,23,Afternoon,0,2,2,2
362,362,Sarrià-Sant Gervasi,Saturday,January,7,Morning,1,2,3,13
567,567,Nou Barris,Friday,June,2,Morning,0,1,1,3
227,227,Eixample,Friday,April,14,Morning,0,1,1,1
380,380,Eixample,Saturday,January,7,Morning,0,1,1,2
202,202,Eixample,Sunday,April,16,Morning,1,1,2,2
375,375,Les Corts,Saturday,January,7,Night,2,1,3,1
457,457,Eixample,Saturday,April,29,Night,1,1,2,3
372,372,Eixample,Saturday,January,7,Night,0,1,1,1
110,110,Eixample,Friday,September,22,Morning,0,1,1,1
271,271,Les Corts,Monday,September,11,Afternoon,0,1,1,2
512,512,Eixample,Sunday,June,4,Morning,0,1,1,3
520,520,Nou Barris,Monday,June,5,Afternoon,0,1,1,1
252,252,Nou Barris,Saturday,April,15,Night,0,1,1,3
464,464,Sants-Montjuïc,Monday,May,1,Night,1,0,1,1
440,440,Eixample,Friday,April,28,Afternoon,1,0,1,2
461,461,Sant Martí,Monday,May,1,Night,0,0,0,3
462,462,Eixample,Monday,May,1,Morning,1,0,1,2
463,463,Eixample,Monday,May,1,Night,1,0,1,2
439,439,Eixample,Saturday,April,29,Afternoon,3,0,3,3
465,465,Eixample,Monday,May,1,Afternoon,1,0,1,2
459,459,Sarrià-Sant Gervasi,Saturday,April,29,Afternoon,1,0,1,2
466,466,Sants-Montjuïc,Monday,May,1,Night,0,0,0,3
467,467,Nou Barris,Monday,May,1,Night,2,0,2,2
438,438,Sant Andreu,Sunday,April,30,Morning,0,0,0,4
468,468,Sant Martí,Monday,May,1,Night,0,0,0,2
469,469,Nou Barris,Monday,May,1,Night,3,0,3,2
470,470,Ciutat Vella,Monday,May,1,Morning,1,0,1,2
460,460,Horta-Guinardó,Sunday,April,30,Afternoon,1,0,1,2

In [26]:
holiday_acc["Serious injuries"].sum()

20

In [28]:
no_hol = pd.read_csv("datasets/1.-Transportation/accidents-without-holidays.csv")

In [29]:
no_hol["Serious injuries"].sum()

221

In [36]:
no_hol['Day'] = no_hol.Day.astype(str)

In [37]:
no_hol["Date"] = no_hol["Month"] + " " + no_hol["Day"]

In [38]:
no_hol.head()

,Unnamed: 0,District Name,Weekday,Month,Day,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Date
0,0,Unknown,Friday,October,13,Morning,2,0,2,2,October 13
1,1,Unknown,Friday,September,1,Morning,2,0,2,2,September 1
2,3,Unknown,Friday,July,21,Night,1,0,1,2,July 21
3,4,Sant Martí,Thursday,May,25,Afternoon,1,0,1,3,May 25
4,5,Sant Martí,Wednesday,September,20,Morning,1,0,1,2,September 20

In [39]:
new_no_hol = no_hol.to_csv("datasets/1.-Transportation/new_no_hol.csv")